services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge