services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"  # Map port 80 in the container to port 4200 on the host
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge