version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://portfolio-db.cb26oqmg4wco.us-east-1.rds.amazonaws.com:3306/portfolio?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "80:80"

  mysql:
    image: mysql:9.1.0
    environment:
      MYSQL_ROOT_PASSWORD: aj477PAJQmVyLsc
      MYSQL_DATABASE: portfolio
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
