version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m

networks:
  app-network:
    driver: bridge