services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1024m
    volumes:
      - .:/app
      - maven_cache:/root/.m2

networks:
  app-network:
    driver: bridge

volumes:
  maven_cache:
    driver: local