name: Deploy Backend and Frontend

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev 

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: cd backend/java/ && mvn package

      - name: Install AWS CLI
        run: sudo apt-get install awscli -y

      - name: Deploy to Elastic Beanstalk
        run: |
          zip -r deployment.zip backend/java/target/*.jar
          aws elasticbeanstalk create-application-version \
            --application-name PortfolioBackendAPI \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=PortfolioBackendAPISpringBoot-env,S3Key=deployment.zip \
            --region eu-west-1
          aws elasticbeanstalk update-environment \
            --environment-name PortfolioBackendAPISpringBoot-env \
            --version-label ${{ github.sha }} \
            --region eu-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.1.0'
          
      - name: Install Angular CLI
        run: npm install -g @angular/cli@latest

      - name: Install AWS CLI
        run: sudo apt-get install awscli -y

      - name: Configure AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID && \
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY && \
          aws configure set default.region us-east-1

      - name: Build Angular App
        run: |
          cd frontend/angular/ 
          npm install --force
          ng build --configuration production

      - name: Deploy to S3
        run: |
          aws s3 sync frontend/angular/dist/frontend s3://my-portfolio-frontend-khovakrishna --delete
