name: Deploy Backend and Frontend

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  pages: write
  id-token: write 

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Navigate to the backend/java subfolder
        run: cd backend/java/
        
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          project_path: backend/java
          dontuseforce: false      

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: frontend/angular/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/angular/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.1.0'

      - name: Install Angular CLI
        run: npm install -g @angular/cli@latest

      - name: Install Dependencies
        run: |
          cd frontend/angular/
          npm ci --force

      - name: Build Angular App
        run: |
          cd frontend/angular/
          ng build --configuration production

      - name: Deploy to GitHub Pages
        run: |
          cd frontend/angular/dist/frontend/browser  # Navigate to the build output directory
          git init  # Initialize a new Git repository
          git config user.email "krishnak.pilato@gmail.com"  # Change to your email
          git config user.name "krishnapilato"  # Change to your name
          git add .  # Add all files to the staging area
          git commit -m "Deploy frontend to GitHub Pages"  # Commit the changes
          git push --force --set-upstream https://x-access-token:${{ secrets.TOKEN }}@github.com/krishnapilato/portfolio.git master:gh-pages  # Push to gh-pages branch
